### ISSUE TITLE
Is this tutorial obsolete?

### ISSUE THREAD

**Issue by fitbodylife** [ParsePlatform/SavingImagesTutorial#6]
Is this tutorial and  your other ios tutorials obsolete?  i've tried to do 3 of them and they're all broken.  non will compile and they have a bunch of parsing errors that xcode can't debug.

**Comment by html5cat** [comment]
@fitbodylife sorry for the delay on this one, we are going through a refresh of materials and will update/remove obsolete tutorials soon!
